name: Optimize Images

on:
  workflow_dispatch:
  push:
    paths:
      - 'images/**'

jobs:
  optimize:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Optimize images
        uses: jessfraz/imagemin-action@v1
        with:
          source_dir: 'images'
          dest_dir: 'images'

      - name: Commit optimized images
        uses: EndBug/add-and-commit@v9
        with:
          message: 'chore(images): optimize images'
          add: 'images'
          author_name: 'github-actions'
          author_email: 'actions@github.com'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}